name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    types: [opened, edited]
    branches: ["main/**"]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            hoodnoah/OpenCvSharp_Docker
          tags: | 
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build and Push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          platforms: linux/amd64, linux/arm/v7, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
